---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible_role_intellij_jdks_centos
    image: centos:7
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible

verifier:
  name: testinfra
