---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create test users
      become: yes
      user:
        name: '{{ item }}'
        state: present
        home: '/home/{{ item }}'
        createhome: yes
      with_items:
        - test_usr
        - test_usr2

    - name: install test dependencies
      become: yes
      yum:
        name:
          - which
          - java-1.8.0-openjdk-devel
          - java-1.8.0-openjdk-src
          - java-11-openjdk-devel
          - java-11-openjdk-jmods
          - java-11-openjdk-src
        state: present

    - name: set facts for openjdk locations
      set_fact:
        jdk8_home: '/usr/lib/jvm/java-1.8.0-openjdk'
        jdk11_home: '/usr/lib/jvm/java-11-openjdk'

  roles:
    - role: ansible_role_intellij_jdks
      intellij_jdks_intellij_user_config_dir: '.config/JetBrains/IntelliJIdea2020.1'
      users:
        - username: test_usr
          intellij_jdks:
            - name: '1.8'
              home: '{{ jdk8_home }}'
            - name: '11'
              home: '{{ jdk11_home }}'
          intellij_jdks_default: '1.8'
        - username: test_usr2
