---
- name: Converge
  hosts: all

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      changed_when: no

    - name: create test users
      become: yes
      user:
        name: '{{ item }}'
        state: present
        home: '/home/{{ item }}'
        createhome: yes
      with_items:
        - test_usr
        - test_usr2

    - name: install test dependencies
      become: yes
      apt:
        name:
          - openjdk-8-jdk
          - openjdk-8-source
          - openjdk-11-jdk
          - openjdk-11-source
        state: present

    - name: set facts for openjdk locations
      set_fact:
        jdk8_home: '/usr/lib/jvm/java-1.8.0-openjdk-amd64'
        jdk11_home: '/usr/lib/jvm/java-11-openjdk-amd64'

  roles:
    - role: ansible_role_intellij_jdks
      intellij_jdks_intellij_user_config_dir: '.config/JetBrains/IntelliJIdea2020.1'
      users:
        - username: test_usr
          intellij_jdks:
            - name: '1.8'
              home: '{{ jdk8_home }}'
            - name: '11'
              home: '{{ jdk11_home }}'
          intellij_jdks_default: '1.8'
        - username: test_usr2
