---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create test users
      become: yes
      user:
        name: '{{ item }}'
        state: present
        home: '/home/{{ item }}'
        createhome: yes
      with_items:
        - test_usr
        - test_usr2

    - name: install jdk 8
      become: yes
      apt:
        name: openjdk-8-jdk
        state: present

    - name: install jdk 8 source
      become: yes
      apt:
        name: openjdk-8-source
        state: present

    - name: create jdk 11 installation directory
      become: yes
      file:
        state: directory
        owner: root
        group: root
        mode: 'u=rwx,go=rx'
        dest: '/opt/java/jdk-11'

    - name: download jdk 11
      get_url:
        url: 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=hotspot&os=linux&arch=x64&release=jdk-11.0.3%2B7&type=jdk'
        dest: '/opt/java/jdk-11.tar.gz'
        force: no
        use_proxy: yes
        validate_certs: yes
        timeout: 360
        mode: 'u=rw,go=r'

    - name: install jdk 11
      become: yes
      unarchive:
        src: '/opt/java/jdk-11.tar.gz'
        remote_src: yes
        dest: '/opt/java/jdk-11'
        owner: root
        group: root
        creates: '/opt/java/jdk-11/jdk-11.0.3+7/bin'

    - name: set facts for openjdk locations
      set_fact:
        jdk8_home: '/usr/lib/jvm/java-1.8.0-openjdk-amd64'
        jdk11_home: '/opt/java/jdk-11/jdk-11.0.3+7'

  roles:
    - role: ansible_role_intellij_jdks
      intellij_jdks_intellij_user_config_dir: '.config/JetBrains/IntelliJIdea2020.1'
      users:
        - username: test_usr
          intellij_jdks:
            - name: '1.8'
              home: '{{ jdk8_home }}'
            - name: '11'
              home: '{{ jdk11_home }}'
          intellij_jdks_default: '1.8'
        - username: test_usr2
